/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SortieRouteImport } from './routes/sortie'
import { Route as NewsRouteImport } from './routes/news'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as InvasionsRouteImport } from './routes/invasions'
import { Route as FissuresRouteImport } from './routes/fissures'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CyclesRouteImport } from './routes/cycles'
import { Route as BountiesRouteImport } from './routes/bounties'
import { Route as ArchonHuntRouteImport } from './routes/archon-hunt'
import { Route as ArbitrationRouteImport } from './routes/arbitration'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as DemoStoreRouteImport } from './routes/demo/store'
import { Route as DemoMcpTodosRouteImport } from './routes/demo/mcp-todos'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'
import { Route as DemoApiTqTodosRouteImport } from './routes/demo/api.tq-todos'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as DemoApiMcpTodosRouteImport } from './routes/demo/api.mcp-todos'
import { Route as ApiWarframeWorldstateRouteImport } from './routes/api/warframe/worldstate'
import { Route as ApiWarframeSpIncursionsTodayRouteImport } from './routes/api/warframe/sp-incursions-today'
import { Route as ApiWarframeSortieRouteImport } from './routes/api/warframe/sortie'
import { Route as ApiWarframeResolveItemsRouteImport } from './routes/api/warframe/resolve-items'
import { Route as ApiWarframeNewsRouteImport } from './routes/api/warframe/news'
import { Route as ApiWarframeInvasionsRouteImport } from './routes/api/warframe/invasions'
import { Route as ApiWarframeFissuresRouteImport } from './routes/api/warframe/fissures'
import { Route as ApiWarframeEventsRouteImport } from './routes/api/warframe/events'
import { Route as ApiWarframeCyclesRouteImport } from './routes/api/warframe/cycles'
import { Route as ApiWarframeBountiesRouteImport } from './routes/api/warframe/bounties'
import { Route as ApiWarframeArchonHuntRouteImport } from './routes/api/warframe/archonHunt'
import { Route as ApiWarframeArbitrationRouteImport } from './routes/api/warframe/arbitration'
import { Route as ApiWarframeAlertsRouteImport } from './routes/api/warframe/alerts'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const SortieRoute = SortieRouteImport.update({
  id: '/sortie',
  path: '/sortie',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const InvasionsRoute = InvasionsRouteImport.update({
  id: '/invasions',
  path: '/invasions',
  getParentRoute: () => rootRouteImport,
} as any)
const FissuresRoute = FissuresRouteImport.update({
  id: '/fissures',
  path: '/fissures',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CyclesRoute = CyclesRouteImport.update({
  id: '/cycles',
  path: '/cycles',
  getParentRoute: () => rootRouteImport,
} as any)
const BountiesRoute = BountiesRouteImport.update({
  id: '/bounties',
  path: '/bounties',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchonHuntRoute = ArchonHuntRouteImport.update({
  id: '/archon-hunt',
  path: '/archon-hunt',
  getParentRoute: () => rootRouteImport,
} as any)
const ArbitrationRoute = ArbitrationRouteImport.update({
  id: '/arbitration',
  path: '/arbitration',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStoreRoute = DemoStoreRouteImport.update({
  id: '/demo/store',
  path: '/demo/store',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoMcpTodosRoute = DemoMcpTodosRouteImport.update({
  id: '/demo/mcp-todos',
  path: '/demo/mcp-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiTqTodosRoute = DemoApiTqTodosRouteImport.update({
  id: '/demo/api/tq-todos',
  path: '/demo/api/tq-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiMcpTodosRoute = DemoApiMcpTodosRouteImport.update({
  id: '/demo/api/mcp-todos',
  path: '/demo/api/mcp-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWarframeWorldstateRoute = ApiWarframeWorldstateRouteImport.update({
  id: '/api/warframe/worldstate',
  path: '/api/warframe/worldstate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWarframeSpIncursionsTodayRoute =
  ApiWarframeSpIncursionsTodayRouteImport.update({
    id: '/api/warframe/sp-incursions-today',
    path: '/api/warframe/sp-incursions-today',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWarframeSortieRoute = ApiWarframeSortieRouteImport.update({
  id: '/api/warframe/sortie',
  path: '/api/warframe/sortie',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWarframeResolveItemsRoute = ApiWarframeResolveItemsRouteImport.update({
  id: '/api/warframe/resolve-items',
  path: '/api/warframe/resolve-items',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWarframeNewsRoute = ApiWarframeNewsRouteImport.update({
  id: '/api/warframe/news',
  path: '/api/warframe/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWarframeInvasionsRoute = ApiWarframeInvasionsRouteImport.update({
  id: '/api/warframe/invasions',
  path: '/api/warframe/invasions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWarframeFissuresRoute = ApiWarframeFissuresRouteImport.update({
  id: '/api/warframe/fissures',
  path: '/api/warframe/fissures',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWarframeEventsRoute = ApiWarframeEventsRouteImport.update({
  id: '/api/warframe/events',
  path: '/api/warframe/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWarframeCyclesRoute = ApiWarframeCyclesRouteImport.update({
  id: '/api/warframe/cycles',
  path: '/api/warframe/cycles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWarframeBountiesRoute = ApiWarframeBountiesRouteImport.update({
  id: '/api/warframe/bounties',
  path: '/api/warframe/bounties',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWarframeArchonHuntRoute = ApiWarframeArchonHuntRouteImport.update({
  id: '/api/warframe/archonHunt',
  path: '/api/warframe/archonHunt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWarframeArbitrationRoute = ApiWarframeArbitrationRouteImport.update({
  id: '/api/warframe/arbitration',
  path: '/api/warframe/arbitration',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWarframeAlertsRoute = ApiWarframeAlertsRouteImport.update({
  id: '/api/warframe/alerts',
  path: '/api/warframe/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/arbitration': typeof ArbitrationRoute
  '/archon-hunt': typeof ArchonHuntRoute
  '/bounties': typeof BountiesRoute
  '/cycles': typeof CyclesRoute
  '/events': typeof EventsRoute
  '/fissures': typeof FissuresRoute
  '/invasions': typeof InvasionsRoute
  '/mcp': typeof McpRoute
  '/news': typeof NewsRoute
  '/sortie': typeof SortieRoute
  '/demo/mcp-todos': typeof DemoMcpTodosRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/api/warframe/alerts': typeof ApiWarframeAlertsRoute
  '/api/warframe/arbitration': typeof ApiWarframeArbitrationRoute
  '/api/warframe/archonHunt': typeof ApiWarframeArchonHuntRoute
  '/api/warframe/bounties': typeof ApiWarframeBountiesRoute
  '/api/warframe/cycles': typeof ApiWarframeCyclesRoute
  '/api/warframe/events': typeof ApiWarframeEventsRoute
  '/api/warframe/fissures': typeof ApiWarframeFissuresRoute
  '/api/warframe/invasions': typeof ApiWarframeInvasionsRoute
  '/api/warframe/news': typeof ApiWarframeNewsRoute
  '/api/warframe/resolve-items': typeof ApiWarframeResolveItemsRoute
  '/api/warframe/sortie': typeof ApiWarframeSortieRoute
  '/api/warframe/sp-incursions-today': typeof ApiWarframeSpIncursionsTodayRoute
  '/api/warframe/worldstate': typeof ApiWarframeWorldstateRoute
  '/demo/api/mcp-todos': typeof DemoApiMcpTodosRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/arbitration': typeof ArbitrationRoute
  '/archon-hunt': typeof ArchonHuntRoute
  '/bounties': typeof BountiesRoute
  '/cycles': typeof CyclesRoute
  '/events': typeof EventsRoute
  '/fissures': typeof FissuresRoute
  '/invasions': typeof InvasionsRoute
  '/mcp': typeof McpRoute
  '/news': typeof NewsRoute
  '/sortie': typeof SortieRoute
  '/demo/mcp-todos': typeof DemoMcpTodosRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/api/warframe/alerts': typeof ApiWarframeAlertsRoute
  '/api/warframe/arbitration': typeof ApiWarframeArbitrationRoute
  '/api/warframe/archonHunt': typeof ApiWarframeArchonHuntRoute
  '/api/warframe/bounties': typeof ApiWarframeBountiesRoute
  '/api/warframe/cycles': typeof ApiWarframeCyclesRoute
  '/api/warframe/events': typeof ApiWarframeEventsRoute
  '/api/warframe/fissures': typeof ApiWarframeFissuresRoute
  '/api/warframe/invasions': typeof ApiWarframeInvasionsRoute
  '/api/warframe/news': typeof ApiWarframeNewsRoute
  '/api/warframe/resolve-items': typeof ApiWarframeResolveItemsRoute
  '/api/warframe/sortie': typeof ApiWarframeSortieRoute
  '/api/warframe/sp-incursions-today': typeof ApiWarframeSpIncursionsTodayRoute
  '/api/warframe/worldstate': typeof ApiWarframeWorldstateRoute
  '/demo/api/mcp-todos': typeof DemoApiMcpTodosRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/arbitration': typeof ArbitrationRoute
  '/archon-hunt': typeof ArchonHuntRoute
  '/bounties': typeof BountiesRoute
  '/cycles': typeof CyclesRoute
  '/events': typeof EventsRoute
  '/fissures': typeof FissuresRoute
  '/invasions': typeof InvasionsRoute
  '/mcp': typeof McpRoute
  '/news': typeof NewsRoute
  '/sortie': typeof SortieRoute
  '/demo/mcp-todos': typeof DemoMcpTodosRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/api/warframe/alerts': typeof ApiWarframeAlertsRoute
  '/api/warframe/arbitration': typeof ApiWarframeArbitrationRoute
  '/api/warframe/archonHunt': typeof ApiWarframeArchonHuntRoute
  '/api/warframe/bounties': typeof ApiWarframeBountiesRoute
  '/api/warframe/cycles': typeof ApiWarframeCyclesRoute
  '/api/warframe/events': typeof ApiWarframeEventsRoute
  '/api/warframe/fissures': typeof ApiWarframeFissuresRoute
  '/api/warframe/invasions': typeof ApiWarframeInvasionsRoute
  '/api/warframe/news': typeof ApiWarframeNewsRoute
  '/api/warframe/resolve-items': typeof ApiWarframeResolveItemsRoute
  '/api/warframe/sortie': typeof ApiWarframeSortieRoute
  '/api/warframe/sp-incursions-today': typeof ApiWarframeSpIncursionsTodayRoute
  '/api/warframe/worldstate': typeof ApiWarframeWorldstateRoute
  '/demo/api/mcp-todos': typeof DemoApiMcpTodosRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/arbitration'
    | '/archon-hunt'
    | '/bounties'
    | '/cycles'
    | '/events'
    | '/fissures'
    | '/invasions'
    | '/mcp'
    | '/news'
    | '/sortie'
    | '/demo/mcp-todos'
    | '/demo/store'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/api/warframe/alerts'
    | '/api/warframe/arbitration'
    | '/api/warframe/archonHunt'
    | '/api/warframe/bounties'
    | '/api/warframe/cycles'
    | '/api/warframe/events'
    | '/api/warframe/fissures'
    | '/api/warframe/invasions'
    | '/api/warframe/news'
    | '/api/warframe/resolve-items'
    | '/api/warframe/sortie'
    | '/api/warframe/sp-incursions-today'
    | '/api/warframe/worldstate'
    | '/demo/api/mcp-todos'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/arbitration'
    | '/archon-hunt'
    | '/bounties'
    | '/cycles'
    | '/events'
    | '/fissures'
    | '/invasions'
    | '/mcp'
    | '/news'
    | '/sortie'
    | '/demo/mcp-todos'
    | '/demo/store'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/api/warframe/alerts'
    | '/api/warframe/arbitration'
    | '/api/warframe/archonHunt'
    | '/api/warframe/bounties'
    | '/api/warframe/cycles'
    | '/api/warframe/events'
    | '/api/warframe/fissures'
    | '/api/warframe/invasions'
    | '/api/warframe/news'
    | '/api/warframe/resolve-items'
    | '/api/warframe/sortie'
    | '/api/warframe/sp-incursions-today'
    | '/api/warframe/worldstate'
    | '/demo/api/mcp-todos'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/arbitration'
    | '/archon-hunt'
    | '/bounties'
    | '/cycles'
    | '/events'
    | '/fissures'
    | '/invasions'
    | '/mcp'
    | '/news'
    | '/sortie'
    | '/demo/mcp-todos'
    | '/demo/store'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/api/warframe/alerts'
    | '/api/warframe/arbitration'
    | '/api/warframe/archonHunt'
    | '/api/warframe/bounties'
    | '/api/warframe/cycles'
    | '/api/warframe/events'
    | '/api/warframe/fissures'
    | '/api/warframe/invasions'
    | '/api/warframe/news'
    | '/api/warframe/resolve-items'
    | '/api/warframe/sortie'
    | '/api/warframe/sp-incursions-today'
    | '/api/warframe/worldstate'
    | '/demo/api/mcp-todos'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  ArbitrationRoute: typeof ArbitrationRoute
  ArchonHuntRoute: typeof ArchonHuntRoute
  BountiesRoute: typeof BountiesRoute
  CyclesRoute: typeof CyclesRoute
  EventsRoute: typeof EventsRoute
  FissuresRoute: typeof FissuresRoute
  InvasionsRoute: typeof InvasionsRoute
  McpRoute: typeof McpRoute
  NewsRoute: typeof NewsRoute
  SortieRoute: typeof SortieRoute
  DemoMcpTodosRoute: typeof DemoMcpTodosRoute
  DemoStoreRoute: typeof DemoStoreRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  ApiWarframeAlertsRoute: typeof ApiWarframeAlertsRoute
  ApiWarframeArbitrationRoute: typeof ApiWarframeArbitrationRoute
  ApiWarframeArchonHuntRoute: typeof ApiWarframeArchonHuntRoute
  ApiWarframeBountiesRoute: typeof ApiWarframeBountiesRoute
  ApiWarframeCyclesRoute: typeof ApiWarframeCyclesRoute
  ApiWarframeEventsRoute: typeof ApiWarframeEventsRoute
  ApiWarframeFissuresRoute: typeof ApiWarframeFissuresRoute
  ApiWarframeInvasionsRoute: typeof ApiWarframeInvasionsRoute
  ApiWarframeNewsRoute: typeof ApiWarframeNewsRoute
  ApiWarframeResolveItemsRoute: typeof ApiWarframeResolveItemsRoute
  ApiWarframeSortieRoute: typeof ApiWarframeSortieRoute
  ApiWarframeSpIncursionsTodayRoute: typeof ApiWarframeSpIncursionsTodayRoute
  ApiWarframeWorldstateRoute: typeof ApiWarframeWorldstateRoute
  DemoApiMcpTodosRoute: typeof DemoApiMcpTodosRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoApiTqTodosRoute: typeof DemoApiTqTodosRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sortie': {
      id: '/sortie'
      path: '/sortie'
      fullPath: '/sortie'
      preLoaderRoute: typeof SortieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invasions': {
      id: '/invasions'
      path: '/invasions'
      fullPath: '/invasions'
      preLoaderRoute: typeof InvasionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fissures': {
      id: '/fissures'
      path: '/fissures'
      fullPath: '/fissures'
      preLoaderRoute: typeof FissuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cycles': {
      id: '/cycles'
      path: '/cycles'
      fullPath: '/cycles'
      preLoaderRoute: typeof CyclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bounties': {
      id: '/bounties'
      path: '/bounties'
      fullPath: '/bounties'
      preLoaderRoute: typeof BountiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archon-hunt': {
      id: '/archon-hunt'
      path: '/archon-hunt'
      fullPath: '/archon-hunt'
      preLoaderRoute: typeof ArchonHuntRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arbitration': {
      id: '/arbitration'
      path: '/arbitration'
      fullPath: '/arbitration'
      preLoaderRoute: typeof ArbitrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/store': {
      id: '/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof DemoStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/mcp-todos': {
      id: '/demo/mcp-todos'
      path: '/demo/mcp-todos'
      fullPath: '/demo/mcp-todos'
      preLoaderRoute: typeof DemoMcpTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/tq-todos': {
      id: '/demo/api/tq-todos'
      path: '/demo/api/tq-todos'
      fullPath: '/demo/api/tq-todos'
      preLoaderRoute: typeof DemoApiTqTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/mcp-todos': {
      id: '/demo/api/mcp-todos'
      path: '/demo/api/mcp-todos'
      fullPath: '/demo/api/mcp-todos'
      preLoaderRoute: typeof DemoApiMcpTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/warframe/worldstate': {
      id: '/api/warframe/worldstate'
      path: '/api/warframe/worldstate'
      fullPath: '/api/warframe/worldstate'
      preLoaderRoute: typeof ApiWarframeWorldstateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/warframe/sp-incursions-today': {
      id: '/api/warframe/sp-incursions-today'
      path: '/api/warframe/sp-incursions-today'
      fullPath: '/api/warframe/sp-incursions-today'
      preLoaderRoute: typeof ApiWarframeSpIncursionsTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/warframe/sortie': {
      id: '/api/warframe/sortie'
      path: '/api/warframe/sortie'
      fullPath: '/api/warframe/sortie'
      preLoaderRoute: typeof ApiWarframeSortieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/warframe/resolve-items': {
      id: '/api/warframe/resolve-items'
      path: '/api/warframe/resolve-items'
      fullPath: '/api/warframe/resolve-items'
      preLoaderRoute: typeof ApiWarframeResolveItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/warframe/news': {
      id: '/api/warframe/news'
      path: '/api/warframe/news'
      fullPath: '/api/warframe/news'
      preLoaderRoute: typeof ApiWarframeNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/warframe/invasions': {
      id: '/api/warframe/invasions'
      path: '/api/warframe/invasions'
      fullPath: '/api/warframe/invasions'
      preLoaderRoute: typeof ApiWarframeInvasionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/warframe/fissures': {
      id: '/api/warframe/fissures'
      path: '/api/warframe/fissures'
      fullPath: '/api/warframe/fissures'
      preLoaderRoute: typeof ApiWarframeFissuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/warframe/events': {
      id: '/api/warframe/events'
      path: '/api/warframe/events'
      fullPath: '/api/warframe/events'
      preLoaderRoute: typeof ApiWarframeEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/warframe/cycles': {
      id: '/api/warframe/cycles'
      path: '/api/warframe/cycles'
      fullPath: '/api/warframe/cycles'
      preLoaderRoute: typeof ApiWarframeCyclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/warframe/bounties': {
      id: '/api/warframe/bounties'
      path: '/api/warframe/bounties'
      fullPath: '/api/warframe/bounties'
      preLoaderRoute: typeof ApiWarframeBountiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/warframe/archonHunt': {
      id: '/api/warframe/archonHunt'
      path: '/api/warframe/archonHunt'
      fullPath: '/api/warframe/archonHunt'
      preLoaderRoute: typeof ApiWarframeArchonHuntRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/warframe/arbitration': {
      id: '/api/warframe/arbitration'
      path: '/api/warframe/arbitration'
      fullPath: '/api/warframe/arbitration'
      preLoaderRoute: typeof ApiWarframeArbitrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/warframe/alerts': {
      id: '/api/warframe/alerts'
      path: '/api/warframe/alerts'
      fullPath: '/api/warframe/alerts'
      preLoaderRoute: typeof ApiWarframeAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  ArbitrationRoute: ArbitrationRoute,
  ArchonHuntRoute: ArchonHuntRoute,
  BountiesRoute: BountiesRoute,
  CyclesRoute: CyclesRoute,
  EventsRoute: EventsRoute,
  FissuresRoute: FissuresRoute,
  InvasionsRoute: InvasionsRoute,
  McpRoute: McpRoute,
  NewsRoute: NewsRoute,
  SortieRoute: SortieRoute,
  DemoMcpTodosRoute: DemoMcpTodosRoute,
  DemoStoreRoute: DemoStoreRoute,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  ApiWarframeAlertsRoute: ApiWarframeAlertsRoute,
  ApiWarframeArbitrationRoute: ApiWarframeArbitrationRoute,
  ApiWarframeArchonHuntRoute: ApiWarframeArchonHuntRoute,
  ApiWarframeBountiesRoute: ApiWarframeBountiesRoute,
  ApiWarframeCyclesRoute: ApiWarframeCyclesRoute,
  ApiWarframeEventsRoute: ApiWarframeEventsRoute,
  ApiWarframeFissuresRoute: ApiWarframeFissuresRoute,
  ApiWarframeInvasionsRoute: ApiWarframeInvasionsRoute,
  ApiWarframeNewsRoute: ApiWarframeNewsRoute,
  ApiWarframeResolveItemsRoute: ApiWarframeResolveItemsRoute,
  ApiWarframeSortieRoute: ApiWarframeSortieRoute,
  ApiWarframeSpIncursionsTodayRoute: ApiWarframeSpIncursionsTodayRoute,
  ApiWarframeWorldstateRoute: ApiWarframeWorldstateRoute,
  DemoApiMcpTodosRoute: DemoApiMcpTodosRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoApiTqTodosRoute: DemoApiTqTodosRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
